backend:
  name: git-gateway
  branch: main # Assurez-vous que votre branche est bien 'main'

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://www.maison-mb.fr
display_url: https://www.maison-mb.fr

collections:
  - name: "blog"
    label: "Articles de Blog (SEO)"
    label_singular: "Article"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre de l'article", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Image de couverture", name: "image", widget: "image", required: false}
      - {label: "Description SEO (Meta)", name: "description", widget: "text", hint: "Texte court pour Google (max 160 caractères)"}
      - {label: "Contenu", name: "body", widget: "markdown"}
