backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Actualités"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre de l'article", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé (SEO)", name: "description", widget: "string"}
      - {label: "Contenu de l'article", name: "body", widget: "markdown"}
