title: Maison MB Rénovation
description: L'Excellence de la Rénovation en Île-de-France
url: "https://maison-mb.fr"
baseurl: ""

# Configuration pour GitHub Pages
markdown: kramdown
permalink: /:title/
encoding: "utf-8"
